### PR TITLE
Fix typo in error message

### PR DESCRIPTION
**Pull request by dakinggg**

### CODE REVIEW

**Comment by dakinggg** [comment]
@adrianeboyd @ines ?

**Comment by svlandeg** [comment]
Thanks for the PR! Please don't ping individual people though - it's unnecessary and makes our Github mentions really hard to use.

**Comment by svlandeg** [comment]
Clearly the mypy error is unrelated to this PR, but let me see if I can fix it first...

**Comment by svlandeg** [comment]
@dakinggg: the `master` you originally made this PR to (and the other PR) was already set up for 3.0.x, removing Python 3.6 and 3.7. However - that's not the version that spaCy currently expects. I've moved the branches around so that `master` points back to the 2.0.x releases, but this inadvertently adds artificial commits to this PR. I'll probably create a clean PR with your commit to the new `master` to resolve.

**Pull request closed without merging**
